# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 186e78111c0599cde5b23bc3076e619bfb7042eadfb175600436ebd356c13791fa81f6dc03d750b0326f9a69c09f38cdabea2b40150e4fe210a3a86ce86140b2

test:
  secret_key_base: 4126b9c97fa8eae2bf17479ba771ce8de6494d135e2918e16f51ac86dd516cb809c5cbe9cfb73a20e46d84840f4075a4889b3393c5c62888fc7195451968ecd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
